### ISSUE TITLE
Twitter image problem

### ISSUE THREAD

**Issue by char0n** [Mokkapps/mokkapps#3]
Hi @Mokkapps,

Noticed  that your profile page no longer shows last twitter image due to the problems in `rtweet` library. I found a suitable replacement in https://github.com/gazf/github-readme-twitter. It's simple, doesn't require credentials and works exactly as described. Already implemented it in my GitHub profile page: https://github.com/char0n/char0n

Thought you could find this information usefull.

Have a great rest of the weekend!

**Comment by Mokkapps** [comment]
Hi @char0n, thank you very much for that tip 🚀 I added it to my profile page!

**Comment by char0n** [comment]
Sure thing!
